CREATE TABLE IF NOT EXISTS `work_request_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `work_request_id` INT NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actor_id` INT NULL,
  `actor_type` VARCHAR(50) NULL,
  `actor_name` VARCHAR(255) NULL,
  `actor_email` VARCHAR(255) NULL,
  `previous_status` VARCHAR(50) NULL,
  `new_status` VARCHAR(50) NULL,
  `previous_review` VARCHAR(50) NULL,
  `new_review` VARCHAR(50) NULL,
  `previous_review_stage` VARCHAR(50) NULL,
  `new_review_stage` VARCHAR(50) NULL,
  `previous_data` JSON NULL,
  `changes` JSON NULL,
  `next_data` JSON NULL,
  `comments` TEXT NULL,
  `related_user_id` INT NULL,
  `related_user_name` VARCHAR(255) NULL,
  `related_manager_id` INT NULL,
  `related_task_id` INT NULL,
  `related_issue_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `idx_work_request_history_work_request_id` (`work_request_id`),
  INDEX `idx_work_request_history_actor_id` (`actor_id`),
  INDEX `idx_work_request_history_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `task_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `task_id` INT NOT NULL,
  `work_request_id` INT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actor_id` INT NULL,
  `actor_type` VARCHAR(50) NULL,
  `actor_name` VARCHAR(255) NULL,
  `actor_email` VARCHAR(255) NULL,
  `previous_status` VARCHAR(50) NULL,
  `new_status` VARCHAR(50) NULL,
  `previous_review` VARCHAR(50) NULL,
  `new_review` VARCHAR(50) NULL,
  `previous_review_stage` VARCHAR(50) NULL,
  `new_review_stage` VARCHAR(50) NULL,
  `previous_data` JSON NULL,
  `changes` JSON NULL,
  `next_data` JSON NULL,
  `comments` TEXT NULL,
  `related_user_id` INT NULL,
  `related_user_name` VARCHAR(255) NULL,
  `assigned_to_user_id` INT NULL,
  `assigned_to_user_name` VARCHAR(255) NULL,
  `related_issue_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `idx_task_history_task_id` (`task_id`),
  INDEX `idx_task_history_work_request_id` (`work_request_id`),
  INDEX `idx_task_history_actor_id` (`actor_id`),
  INDEX `idx_task_history_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `issue_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  `issue_assignment_id` INT NOT NULL,
  `task_id` INT NULL,
  `work_request_id` INT NULL,
  `parent_issue_id` INT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actor_id` INT NULL,
  `actor_type` VARCHAR(50) NULL,
  `actor_name` VARCHAR(255) NULL,
  `actor_email` VARCHAR(255) NULL,
  `previous_status` VARCHAR(50) NULL,
  `new_status` VARCHAR(50) NULL,
  `previous_review` VARCHAR(50) NULL,
  `new_review` VARCHAR(50) NULL,
  `previous_review_stage` VARCHAR(50) NULL,
  `new_review_stage` VARCHAR(50) NULL,
  `previous_data` JSON NULL,
  `changes` JSON NULL,
  `next_data` JSON NULL,
  `comments` TEXT NULL,
  `related_user_id` INT NULL,
  `related_user_name` VARCHAR(255) NULL,
  `assigned_to_user_id` INT NULL,
  `assigned_to_user_name` VARCHAR(255) NULL,
  `related_issue_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  INDEX `idx_issue_history_issue_assignment_id` (`issue_assignment_id`),
  INDEX `idx_issue_history_task_id` (`task_id`),
  INDEX `idx_issue_history_work_request_id` (`work_request_id`),
  INDEX `idx_issue_history_actor_id` (`actor_id`),
  INDEX `idx_issue_history_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
